server:
  port: 8081

spring:
  thymeleaf:
    prefix: 'classpath:/templates/'
  application:
    name: boot-demo
#thymeleaf:
#  application:
#    name: boot-demo
eureka:
  client:
#    service-url: {'defaultZone':'http://registryCenter:8084/eureka/'}
     service-url: {'defaultZone':'http://peer1:8084/eureka/,http://peer2:8085/eureka/'}


